# Proyecto minería de Datos

Objetivo de obtener los siguiente indicadores: 

1. Construir un catalogo completo con toda la información complementaria y sin duplicados, Anexar ambos archivos de catalogo. Solo las de tipo de proceso 1.

2. Identificar aquellas piezas donde el costo es mas elevado que el precio al publico.

3. Ver cuantas piezas requiere cada sistema.

4. Ver cuantas piezas son importadas por cada país.

5. Conocer los responsables que no tengan una pieza asignada.

6. Conocer el tiempo de procesamiento por maquina.

## Glosario

- df     -> DataFrame
- concat -> Concatenar o Anexar.
- merge  -> Buscar o combinar consultas. 
- nan    -> Not a number.

In [106]:
# Cargando Librerías
import numpy as np 
import pandas as pd

In [107]:
# Carga de Archivos.
# Los archivos de tipo CSV están codificados en base al formato ISO-8859-1.

df_catalago = pd.read_csv("./Data/BD_CATALOGO.csv",sep=",",encoding='ISO-8859-1')
df_catalago2 = pd.read_csv("./Data/BD_CATALOGO_2.csv",sep=",",encoding='ISO-8859-1')
df_finanzas = pd.read_csv("./Data/BD_FINANZAS.csv",sep=",",encoding='ISO-8859-1')
df_region = pd.read_csv("./Data/BD_REGION.csv",sep=",",encoding='ISO-8859-1')
df_responsables = pd.read_csv("./Data/BD_RESPONSABLES.csv",sep=",",encoding='ISO-8859-1')
df_sistemas = pd.read_csv("./Data/BD_SISTEMAS.csv",sep=",",encoding='ISO-8859-1')

## 1. Construir un catalogo completo con toda la información complementaria y sin duplicados, Anexar ambos archivos de catalogo. Solo las de tipo de proceso 1.

In [108]:
# Anexar el catalogo completo.
df_catalogo_completo =pd.concat([df_catalago,df_catalago2],ignore_index=True)
df_catalogo_completo

,id pieza,nombreee,SISTEMMAA,repsomnsnañbe,id piezas hermnaa,PAISSS,tiempo procesamiento promedio,demanda,tipo proceso,codigo maquinaa
0,1,Válvula de control de flujo,1,1,43,1,662,6353067,1,A33335
1,2,Bomba centrífuga,2,2,14,2,494,8398096,1,A301435
2,3,Motor de corriente continua,3,3,34,3,677,7945222,1,A440087
3,4,Sensor de temperatura,4,4,21,4,685,1134768,1,A39538
4,5,Engranaje planetario,5,5,17,5,276,7205370,1,V495138
...,...,...,...,...,...,...,...,...,...,...
193,41,Elemento de filtro hidráulico,26,41,29,6,55,6225437,1,S259784
194,42,Regulador de presión,20,42,9,1,210,9484466,1,D43567
195,43,Compresor de gas,27,43,28,1,470,6128747,1,A51555
196,44,Sensor de nivel,16,44,32,1,291,5021131,2,A95101
197,45,Válvula de solenoide proporcional,28,45,40,1,123,3792643,2,A568128

In [109]:
# Eliminar duplicados
# El método inplace, sobrescribe los datos sobre el mismo data frame.
df_catalogo_completo.drop_duplicates(inplace=True)

# Filtrado por tipo de proceso 1. 
df_catalogo_completo = df_catalogo_completo[df_catalogo_completo['tipo proceso'] == 1]

In [110]:

df_catalogo_completo

,id pieza,nombreee,SISTEMMAA,repsomnsnañbe,id piezas hermnaa,PAISSS,tiempo procesamiento promedio,demanda,tipo proceso,codigo maquinaa
0,1,Válvula de control de flujo,1,1,43,1,662,6353067,1,A33335
1,2,Bomba centrífuga,2,2,14,2,494,8398096,1,A301435
2,3,Motor de corriente continua,3,3,34,3,677,7945222,1,A440087
3,4,Sensor de temperatura,4,4,21,4,685,1134768,1,A39538
4,5,Engranaje planetario,5,5,17,5,276,7205370,1,V495138
5,6,Compresor de aire,6,6,20,6,181,9389166,1,V405703
6,7,Filtro de aire,7,7,37,7,537,8973529,1,V183148
7,8,Válvula solenoide,8,8,42,8,551,6031700,1,V161669
8,9,Tornillo sin fin,5,9,16,9,56,9300568,1,V499753
9,10,Rodamiento de bolas,9,10,7,10,627,694796,1,V307036
10,11,Calentador eléctrico,10,11,32,11,348,9094490,1,V347135
11,12,Válvula de retención,8,12,11,12,177,6259260,1,V583935
12,13,Cilindro hidráulico,11,13,30,13,404,2947086,1,D252684
13,14,Placa de circuito impreso,12,14,10,14,119,7335024,1,D434597
14,15,Sensor de presión,13,15,31,15,235,9431503,1,D356204
15,16,Bomba de pistón,2,16,28,3,438,3920212,1,D329046
16,17,Válvula de mariposa,8,17,5,1,181,2789983,1,D582443
17,18,Enfriador de aceite,14,18,27,3,524,1006066,1,E27256
18,19,Motor de corriente alterna,3,19,37,1,671,8148173,1,E253731
19,20,Filtro de combustible,15,20,1,3,538,6438126,1,E77747
20,21,Transmisor de nivel,16,21,34,1,162,446192,1,E289276
21,22,Tornillo de bola,5,22,42,1,522,4054570,1,E126883
22,23,Generador eléctrico,17,23,12,13,615,1041723,1,E368112
23,24,Acoplamiento flexible,5,24,1,1,493,3087103,1,F164478
24,25,Sensor de humedad,18,25,39,13,629,1664847,1,F539589
25,26,Válvula de compuerta,8,26,38,13,202,7510176,1,F593054
26,27,Calentador de gas,19,27,11,1,200,6634371,1,F261154
27,28,Motor lineal,3,28,10,12,226,5156632,1,F19161
28,29,Bomba de diafragma,2,29,43,12,307,3718128,1,F117194
29,30,Interruptor de presión,13,30,7,1,105,6551522,1,S371877
30,31,Válvula de alivio,20,31,15,12,617,9051918,1,S175963
31,32,Filtro de agua,21,32,35,1,693,8809639,1,S354820
32,33,Motor paso a paso,3,33,33,1,592,5168176,1,S213370
33,34,Válvula de bola,8,34,44,1,50,3022565,1,S87898
34,35,Sensor de flujo,22,35,35,1,365,7072786,1,S343417
35,36,Cilindro neumático,23,36,40,4,481,6288214,1,S578961
36,37,Manguera de alta presión,24,37,20,5,504,9224027,1,F138462
37,38,Sonda de temperatura,4,38,36,6,6,2325963,1,F367782
38,39,Transductor de presión,13,39,15,7,283,4453517,1,F119275
39,40,Válvula de control direccional,25,40,16,7,5,6661394,1,S238258
40,41,Elemento de filtro hidráulico,26,41,29,6,55,6225437,1,S259784
41,42,Regulador de presión,20,42,9,1,210,9484466,1,D43567
42,43,Compresor de gas,27,43,28,1,470,6128747,1,A51555

## 2. - Identificar aquellas piezas donde el costo es mas elevado que el precio al publico.

In [111]:
df_finanzas.head()

   ID_PIEZA  COSTO  PRECIO
0         1   4171    3587
1         2   3499    7538
2         3   5677    7620
3         4   3793    4600
4         5   5332    6422

In [112]:
# Comprobando que ambas partes compartan el mismo tipo de datos donde se va a hacer la merge. 
# En este caso se utiliza ID_PIEZA (df_finanzas) con id pieza (df_catalogo_completo)
df_finanzas.dtypes

ID_PIEZA    int64
COSTO       int64
PRECIO      int64
dtype: object

In [113]:
df_catalogo_completo.dtypes

id pieza                          int64
nombreee                         object
SISTEMMAA                         int64
repsomnsnañbe                     int64
id piezas hermnaa                 int64
PAISSS                            int64
tiempo procesamiento promedio     int64
demanda                           int64
tipo proceso                      int64
codigo maquinaa                  object
dtype: object

In [114]:
# Merge al data frame catalogo completo con el df de finanzas. 
# Por default es inner join. -> para mas info ir a notas en la parte de merge.
df_catalogo_completo = df_catalogo_completo.merge(df_finanzas, left_on='id pieza',right_on='ID_PIEZA')

In [115]:
df_catalogo_completo.head(5)

,id pieza,nombreee,SISTEMMAA,repsomnsnañbe,id piezas hermnaa,PAISSS,tiempo procesamiento promedio,demanda,tipo proceso,codigo maquinaa,ID_PIEZA,COSTO,PRECIO
0,1,Válvula de control de flujo,1,1,43,1,662,6353067,1,A33335,1,4171,3587
1,2,Bomba centrífuga,2,2,14,2,494,8398096,1,A301435,2,3499,7538
2,3,Motor de corriente continua,3,3,34,3,677,7945222,1,A440087,3,5677,7620
3,4,Sensor de temperatura,4,4,21,4,685,1134768,1,A39538,4,3793,4600
4,5,Engranaje planetario,5,5,17,5,276,7205370,1,V495138,5,5332,6422

In [116]:
# Productos de los cuales tienen un costo mayor al precio de venta. 
df_costo_mayor = df_catalogo_completo[df_catalogo_completo['COSTO']> df_catalogo_completo['PRECIO']]

## 3. Ver cuantas piezas requiere cada sistema.

In [117]:
# Merge con df_sistemas para extraer la información necesaria. 
df_catalogo_completo = df_catalogo_completo.merge(df_sistemas,left_on='SISTEMMAA',right_on='ID_SISTEMA')

In [118]:
# Agregando la columna count, para hacer el conteo de valores. 
df_catalogo_completo['count'] = 1 
df_catalogo_completo.head(10)

,id pieza,nombreee,SISTEMMAA,repsomnsnañbe,id piezas hermnaa,PAISSS,tiempo procesamiento promedio,demanda,tipo proceso,codigo maquinaa,ID_PIEZA,COSTO,PRECIO,ID_SISTEMA,SISTEMA_DESC,count
0,1,Válvula de control de flujo,1,1,43,1,662,6353067,1,A33335,1,4171,3587,1,Sistema de control de procesos,1
1,2,Bomba centrífuga,2,2,14,2,494,8398096,1,A301435,2,3499,7538,2,Sistema de bombeo,1
2,16,Bomba de pistón,2,16,28,3,438,3920212,1,D329046,16,3570,7302,2,Sistema de bombeo,1
3,29,Bomba de diafragma,2,29,43,12,307,3718128,1,F117194,29,1443,2351,2,Sistema de bombeo,1
4,3,Motor de corriente continua,3,3,34,3,677,7945222,1,A440087,3,5677,7620,3,Sistema de motores eléctricos,1
5,19,Motor de corriente alterna,3,19,37,1,671,8148173,1,E253731,19,4368,6768,3,Sistema de motores eléctricos,1
6,28,Motor lineal,3,28,10,12,226,5156632,1,F19161,28,2557,2511,3,Sistema de motores eléctricos,1
7,33,Motor paso a paso,3,33,33,1,592,5168176,1,S213370,33,5371,2004,3,Sistema de motores eléctricos,1
8,4,Sensor de temperatura,4,4,21,4,685,1134768,1,A39538,4,3793,4600,4,Sistema de medición y control de temperatura,1
9,38,Sonda de temperatura,4,38,36,6,6,2325963,1,F367782,38,3831,4592,4,Sistema de medición y control de temperatura,1

In [119]:
# Agrupar por Sistemas, para sacar el indicador. 
# .sum() como su nombre lo dice hace la sumatoria de todo las demás columnas. 
# .reset_index() lo que hace es crear un nuevo indice quitando el sistema como indice a la hora de agrupar. 
# el indice son los números que aparecen al inicio de cada dataframe. 
df_sistemas_groupby = df_catalogo_completo.groupby("SISTEMA_DESC").sum().reset_index()

# Renombrando las columnas del data frame.
df_sistemas_groupby.rename(columns={'SISTEMA_DESC':'SISTEMA_DESC','count':'CANTIDAD'},inplace= True)

# Sobrescribiendo para que solo muestra la información de sistema y la cantidad. 
df_sistemas_groupby =df_sistemas_groupby[['SISTEMA_DESC','CANTIDAD']]

In [120]:
df_sistemas_groupby

                                       SISTEMA_DESC  CANTIDAD
0                        Sistema de aire comprimido         1
1                                 Sistema de bombeo         3
2                     Sistema de calefacción de gas         1
3                  Sistema de calefacción eléctrica         1
4                      Sistema de compresión de gas         1
5   Sistema de conducción de fluidos a alta presión         1
6                     Sistema de control de fluidos         5
7                     Sistema de control de presión         2
8                    Sistema de control de procesos         1
9                    Sistema de control electrónico         1
10                    Sistema de control hidráulico         1
11                          Sistema de enfriamiento         1
12             Sistema de filtración de combustible         1
13                 Sistema de filtración hidráulica         1
14       Sistema de generación de energía eléctrica         1
15           Sistema de medición y control de flujo         1
16         Sistema de medición y control de humedad         1
17      Sistema de medición y control de la presión         3
18           Sistema de medición y control de nivel         1
19     Sistema de medición y control de temperatura         2
20                    Sistema de motores eléctricos         4
21                  Sistema de purificación de agua         1
22                  Sistema de purificación de aire         1
23                      Sistema de soporte de carga         1
24     Sistema de transmisión de energía hidráulica         1
25       Sistema de transmisión de energía mecánica         4
26      Sistema de transmisión de energía neumática         1

## 4. Ver cuantas piezas son importadas por cada país.

In [121]:
df_catalogo_completo.head(2)

,id pieza,nombreee,SISTEMMAA,repsomnsnañbe,id piezas hermnaa,PAISSS,tiempo procesamiento promedio,demanda,tipo proceso,codigo maquinaa,ID_PIEZA,COSTO,PRECIO,ID_SISTEMA,SISTEMA_DESC,count
0,1,Válvula de control de flujo,1,1,43,1,662,6353067,1,A33335,1,4171,3587,1,Sistema de control de procesos,1
1,2,Bomba centrífuga,2,2,14,2,494,8398096,1,A301435,2,3499,7538,2,Sistema de bombeo,1

In [122]:
# Eliminar columna repetida.
df_region.drop('ID_REGION.1',axis=1,inplace=True)
df_region.head(2)

   ID_REGION REGION_DESC  CODIGO_IMPORTACION
0          1      México              100591
1          2   Argentina              168532

In [123]:
# Merge para sacar el país y después las importaciones. 
df_catalogo_completo = df_catalogo_completo.merge(df_region,left_on='PAISSS',right_on='ID_REGION')
df_region_groupby = df_catalogo_completo.groupby('REGION_DESC').sum().reset_index()

In [124]:
# Filtrado de Columnas.
df_region_groupby = df_region_groupby[['REGION_DESC','count']]
df_region_groupby

        REGION_DESC  count
0         Argentina      1
1            Brasil      4
2          Bulgaria      1
3             Chile      2
4          Colombia      2
5           Croacia      1
6        Eslovaquia      1
7           Hungría      4
8            México     14
9              Perú      3
10          Polonia      3
11  República Checa      4
12          Rumania      1
13            Rusia      1
14          Ucrania      1

## 5. Conocer los responsables que no tengan una pieza asignada.

In [125]:
# Muestra los valores que existen, y a su vez eliminamos la columna repetida.
df_responsables.head(2)
df_responsables.drop('ID_RESPONSABLE.1',axis=1,inplace=True)

In [126]:
df_responsables.head(2)

   ID_RESPONSABLE     RESPONSABLE_DESC
0               1  Juan Carlos Aguilar
1               2     Ana María García

In [127]:
# Merge para sacar los datos, en este caso usamos el método outer. 
# que permite sacar los datos y los que no encuentra coincidencia los pasa como Nan. 
df_responsables=df_responsables.merge(df_catalogo_completo,left_on='ID_RESPONSABLE',right_on='repsomnsnañbe',how='outer')

In [128]:
df_responsables_sin_pieza = df_responsables[df_responsables['id pieza'].isna()]
df_responsables_sin_pieza = df_responsables_sin_pieza[['ID_RESPONSABLE','RESPONSABLE_DESC']].reset_index()
df_responsables_sin_pieza.drop('index',axis=1,inplace=True)

In [129]:
df_responsables_sin_pieza

    ID_RESPONSABLE          RESPONSABLE_DESC
0               44      Luis Antonio Ramírez
1               45           Isabel González
2               46             Adrián Torres
3               47           Estefanía López
4               48        Salvador Hernández
5               49              Renata Pérez
6               50            Diego González
7               51               Camila Ruiz
8               52     Carlos Eduardo Vargas
9               53           Regina Martínez
10              54              Bruno García
11              55           Karla Fernández
12              56       Julio César Sánchez
13              57             Ximena Castro
14              58            Fabián Mendoza
15              59  María Fernanda Gutiérrez
16              60             Daniel Flores
17              61            Ángela Sánchez
18              62            Leonardo Gómez
19              63            Valeria Torres
20              64         Ricardo Hernández
21              65           Ana Sofía Pérez
22              66   Luis Fernando Rodríguez
23              67          Gabriela Ramírez
24              68         Alejandro Jiménez
25              69           Mariana Vázquez

## 6. Conocer el tiempo de procesamiento por maquina.

In [130]:
df_catalogo_completo.head(3)

,id pieza,nombreee,SISTEMMAA,repsomnsnañbe,id piezas hermnaa,PAISSS,tiempo procesamiento promedio,demanda,tipo proceso,codigo maquinaa,ID_PIEZA,COSTO,PRECIO,ID_SISTEMA,SISTEMA_DESC,count,ID_REGION,REGION_DESC,CODIGO_IMPORTACION
0,1,Válvula de control de flujo,1,1,43,1,662,6353067,1,A33335,1,4171,3587,1,Sistema de control de procesos,1,1,México,100591
1,19,Motor de corriente alterna,3,19,37,1,671,8148173,1,E253731,19,4368,6768,3,Sistema de motores eléctricos,1,1,México,100591
2,33,Motor paso a paso,3,33,33,1,592,5168176,1,S213370,33,5371,2004,3,Sistema de motores eléctricos,1,1,México,100591

In [147]:
df_tiempo_maquina = df_catalogo_completo

# se usa una propiedad del objeto string que permite obtener la primera letra del string, esto es aplicable en este caso.
# debido a que cuando se filtra por [:] solo aplica al axis 0 al primer valor. 
df_tiempo_maquina['Codigo_Maquinaria'] = df_tiempo_maquina['codigo maquinaa'].str.get(0)
df_tiempo_maquina = df_tiempo_maquina.groupby('Codigo_Maquinaria').sum().reset_index()
df_tiempo_maquina = df_tiempo_maquina[['Codigo_Maquinaria','tiempo procesamiento promedio']]
df_tiempo_maquina

  Codigo_Maquinaria  tiempo procesamiento promedio
0                 A                           2988
1                 D                           1587
2                 E                           3032
3                 F                           2850
4                 S                           2963
5                 V                           2753

y con esto finalizamos el ejercicio.